/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dell' at '16-12-23 下午3:26' with Gradle 2.14
 *
 * @author dell, @date 16-12-23 下午3:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
